mode = "map"   # Sets population type. Options are = "map", "gen"

[all]
out_folder = "new"          # any name, output folder will be created with this name
n_iters = 5            # integer > 0

batch_size = 194   # not used yet
data_loc = "C:/Users/BigTuna/Dropbox/par_lgp/penndata/oa.csv"
log_freq = 20_000

mutation_methods = [0]                      # array of ints
compare_methods = [0, 1]                    # array of ints
pop_size =  [1024]                          # array of ints

#    ***  For Map mode only ***
[map]
n_evals = [1000000]
init_pop_size = [50000]
map_methods = [8] #  4 10 11  # 12  13 18 20 21 22  # 13 14 15 18
    [map.kstuff]

    kvals = ["Hi", "I'm", "Kyle"]
    kword = "Hi"

#    ***  For Gen mode  ***
[gen] #hasnt been updated
TOTAL_GENS = [100, 500, 1000]
INIT_GENS = [50, 100, 500]
TOURN_SIZE = [4, 16]